BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: "Up"
            Button:
                text: "Down"
        TextInput:
            id: input_number
    Button:
        text: "Convert Miles to KM"
    Label:
        id: output_label
        font_size: 50
        color: (1, 1, 1, 1)
